### ISSUE TITLE
Create instructions for running a Krustlet node with EKS

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#130]
We should have detailed instructions for configuring and using Krustlet as an EKS node. This first set of instructions does not need to be a fully production ready node (as the project itself isn't ready for full production yet either).

https://github.com/deislabs/krustlet/pull/128 shows documentation for AKS, and the process should largely translate with AWS's services.

**Comment by bacongobbler** [comment]
@jingweno how's your progress coming along? :)

**Comment by peterhuene** [comment]
I'm also attempting to get this working via a hacked-up clone of `https://github.com/awslabs/amazon-eks-ami`.

The idea is that the `install-worker.sh` script will:

1) Install a Rust toolset.
2) Clone and build krustlet.
3) Install krustlet to a known location.
4) Generate the krustlet certificate for HTTPS.
6) Copy a template `kubeconfig` to a known location.
5) Register a systemd service for krustlet that the bootstrap script will start.

It will remove all parts that specifically relate to kubelet and docker.

The `bootstrap.sh` script will:

1. Use the `aws` SDK to fetch cluster information (including the API server certificate).
2. Update the template `kubeconfig` with the cluster information.
3. Start the krustlet service.

I believe this will work because the `kube` crate supports exec actions in `kubeconfig`, which this EKS one will use to retrieve AMI auth tokens for the cluster.

If I get this working, I'll see about opening a PR to this repo to share the knowledge :smile:.

**Comment by peterhuene** [comment]
Oh and in case this wasn't clear, the end result of this would be an AMI that can be used to configure a custom "wasm-running" node group in EKS.

**Comment by peterhuene** [comment]
Unfortunately the base AMI has a libssl 1.0 instead of the 1.1 expected by the release krustlet binary.

We'll just have to build krustlet when building the AMI.

I feel close to getting something working :

**Comment by peterhuene** [comment]
Krustlet works:

```text
$ kubectl get nodes
NAME                                          STATUS   ROLES    AGE    VERSION
ip-XXX-XXX-XXX-XXX.us-west-2.compute.internal   Ready    agent    118s   v1.17.0
```
```
$ kubectl get pods
NAME    READY   STATUS       RESTARTS   AGE
greet   0/1     ExitCode:0   0          2m34s
```

Currently this was using a self-signed server cert, so I can't retreive logs:

```
Error from server: Get https://XXX.XXX.XXX.XXX:10255/containerLogs/default/greet/greet: x509: cannot validate certificate for XXX.XXX.XXX.XXX because it doesn't contain any IP SANs
```

I had to manually edit the `aws-auth` configmap to add the role that I deployed the EKS node group with to get IAM auth working.

Additionally, the default roles don't permit deleting nodes, so the logic in `krustlet` for recreating its node causes the service to fail after a previous service execution.

**Comment by squillace** [comment]
There are numerous failure cases we shall move forward hammering out. Good to know about the role and deletion of nodes, thx.

**Comment by peterhuene** [comment]
I should have a walk-through completed soon, provided I can get the certificate signing working in node bootstrap.

I also discovered [eksctl](https://github.com/weaveworks/eksctl) which has support for custom AMIs and will perform the `aws-auth` configmap editing, so this should be as simple as two commands: one to build the AMI and another to create the cluster with the AMI.

**Comment by peterhuene** [comment]
I was able to get the bootstrap to provision a cluster CA-signed certificate with auto-approval, so `kubectl logs` now works.

Tidying up and then I'll open a PR.  Where do we want the scripts and files that can be used to create an EKS AMI (~9 files) for krustlet to live in the tree?

**Comment by squillace** [comment]
@bacongobbler or @thomastaylor312 ?

**Comment by thomastaylor312** [comment]
I’d recommend a subdir in the howto assets since it is a bunch of files

**Comment by peterhuene** [comment]
I've put up #185 for this issue.
