### ISSUE TITLE
How should Krustlet handle the Container Storage Interface?

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/krustlet#182]
Many of the cloud provider volumes have Container Storage Interface (CSI) plugin implementations to handle mounting volumes to containers. Right now, the attachdetach-controller will attach cloud provider volumes to VMs but will not actually mount the volume. So a few of questions for discussion:

1. Should we implement CSI calls inside of krustlet itself (or at least something similar)?
2. Will it be possible to reuse the current Go plugins or are they too container-centric?
3. Would it be better to leave volume mounting up to individual implementations?
4. Would a good middle ground just be to implement drivers for open source file mounting (NFS, SMB, etc)?

For reference, the CSI docs can be found here: https://kubernetes-csi.github.io/docs/

**Comment by thomastaylor312** [comment]
One other question I have discovered while implementing CSI: Many of the current cloud providers use the "legacy" cloud controller manager. After some initial digging, I am still not sure how those disks get attached to a node in an AKS/EKS/GKE cluster, but it may Just Work™. We should do some investigation/testing with that to see what happens

**Comment by bacongobbler** [comment]
I agree. It's not totally clear how the sausage is made.

As far as I understand the system, most storage class provisioners today are bundled with the cluster. Those "in-tree provisioners" are being deprecated in favour of "external provisioners". The Kubelet is built with the understanding on how to make calls to the correct external provisioner given the provided storage class name.

https://kubernetes.io/docs/concepts/storage/volumes/

With #445, CSI plugins can now register themselves with Krustlet. So we have support right now to register external provisioners like the [azure disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver). The trick is that most documentation recommends running them on every node via a DaemonSet... As a container, naturally.

So there are two calls to action we need to address to support volume mounts via the CSI:

1. Since CSIs are exposed to workloads through a Storage Class, they are referenced through a PersistentVolumeClaim. As I understand it, we currently do not have PVC mount support. We will need to add PVC mount support, which may mean the providers will need to issue CSI calls to provision claims (more research is needed)
2. We will need to document *how* to run a storage class provisioner alongside Krustlet, like the azure disk CSI driver.

To answer your other questions:

> * Will it be possible to reuse the current Go plugins or are they too container-centric?

I believe it will be possible to reuse the current CSI drivers. They were initially written to be run as a DaemonSet on Kubernetes, but the drivers themselves are just a bunch of binaries with a large swath of feature flags.

```
~/code/go/src/sigs.k8s.io/azuredisk-csi-driver ><> make
CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.driverVersion=v0.10.0 -X sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.gitCommit=e2afeb9081e72b2d1f0f106661503349015fca2a -X sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.buildDate=2020-11-25T21:15:22Z -X sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.DriverName=disk.csi.azure.com -X sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.topologyKey=topology.disk.csi.azure.com/zone -extldflags "-static"" -mod vendor -o _output/azurediskplugin ./pkg/azurediskplugin
~/code/go/src/sigs.k8s.io/azuredisk-csi-driver ><> ./_output/azurediskplugin --help
Usage of ./_output/azurediskplugin:
  -add_dir_header
        If true, adds the file directory to the header of the log messages
  -alsologtostderr
        log to standard error as well as files
  -endpoint string
        CSI endpoint (default "unix://tmp/csi.sock")
  -kubeconfig string
        Absolute path to the kubeconfig file. Required only when running out of cluster.
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -metrics-address string
        export the metrics (default "0.0.0.0:29604")
  -nodeid string
        node id
  -one_output
        If true, only write logs to their native severity level (vs also writing to each lower severity level
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -v value
        number for the log level verbosity
  -version
        Print the version and exit.
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

And here's the output running the binary:

```
~/code/go/src/sigs.k8s.io/azuredisk-csi-driver ><> ./_output/azurediskplugin
W1125 13:17:38.731168   50137 main.go:59] nodeid is empty
I1125 13:17:38.731533   50137 azuredisk.go:116]
DRIVER INFORMATION:
-------------------
Build Date: "2020-11-25T21:15:22Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v0.10.0
Git Commit: e2afeb9081e72b2d1f0f106661503349015fca2a
Go Version: go1.15.5
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone

Streaming logs below:
W1125 13:17:38.731578   50137 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E1125 13:17:38.731625   50137 azure.go:72] Failed to load config from file: /etc/kubernetes/azure.json
F1125 13:17:38.731660   50137 azuredisk.go:119] failed to get Azure Cloud Provider, error: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
```

So I believe it's going to be a bit of reverse-engineering to get these working. They appear to be built with some hard-coded values such as where azure.json is located on the filesystem. But once we gain a better understanding of each provisioner, we can bundle these in our HOWTO guides... Or even better, bundle them the same as we do with the Azure ARM templates: https://github.com/deislabs/krustlet/blob/master/contrib/azure/install_krustlet.sh

The simplest external provisioner to set up might be the [local static provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner), so that would be a good one to test with.

**Comment by bacongobbler** [comment]
One other talking point worth mentioning here: there's a new type of volume mount called a [CSI ephemeral volume](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volume). This bit initially threw me into a wild goose chase thinking this was how CSI drivers were mounted to a pod. These types of volumes are considered a beta feature, and I have not seen any mention of them outside of this single document, so it's unclear whether we should consider supporting this type of volume in the future. At the moment my inclination is to steer clear from this until the API is ironed out and the feature is considered GA.

**Comment by kflansburg** [comment]
This is something that I’ve brought up a couple of times. In principle, we should focus on supporting the correct grpc endpoints and configuration of the driver isn’t our problem. Practically, we need some examples for people to try out. In my opinion an easy cheat here is to run Krustlet as a pod or even daemonset inside traditional container nodes. This ensures that all of the relevant drivers are available and configured. This might be the easiest “try it out” option that we could have. Because all of these drivers are shipped as containers, running “heterogenous” nodes may be the true best practice here. If not, the next step might be how to configure a few drivers like you mentioned. This would be required for shipping a VM image that plugs into AKS/ELS
