### ISSUE TITLE
hack/bootstrap.sh blocks on WSL2

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/krustlet#276]
Oddly, calling `just run-wasi` on WSL2 hangs indefinitely. After doing a bit of digging, I found that it was because `hack/bootstrap.sh` blocks on WSL2.

Changing this line:

```
token_secret=$(< /dev/random tr -dc a-z0-9 | head -c${1:-16};echo;)
```

To use `/dev/urandom` instead appears to work:

```
token_secret=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-16};echo;)
```

It looks as though reading from `/dev/random` blocks indefinitely.

**Comment by itowlson** [comment]
Just got bitten by this and confirm changing to `/dev/urandom` fixed it for me.

**Comment by itowlson** [comment]
Also now having a problem doing `just run-wasi` and `just run-wascc` concurrently: 

```
Error: ApiError: certificatesigningrequests.certificates.k8s.io "hestia-tls" already exists: AlreadyExists (ErrorResponse { status: "Failure", message: "certificatesigningrequests.certificates.k8s.io \"hestia-tls\" already exists", reason: "AlreadyExists", code: 409 })

Caused by:
    certificatesigningrequests.certificates.k8s.io "hestia-tls" already exists: AlreadyExists
```

(Here `hestia` is the name of the local machine.)

**Comment by itowlson** [comment]
And I don't know if this is related but I'm now seeing integration tests failing to create the `hello-wasi` pod with an image pull error.  Don't think this is related to anything I've done because I've backed out all my changes... @bacongobbler are you able to run the integration tests on WSL?

**Comment by bacongobbler** [comment]
I saw the same as well. I'll have a look first thing tomorrow!

**Comment by itowlson** [comment]
Pod log message:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"hello-wasi\" in pod \"hello-wasi\" is waiting to start: trying and failing to pull image","reason":"BadRequest","code":400}
```

**Comment by itowlson** [comment]
If I understand this right, it looks like it's trying to schedule it on the `docker-desktop` node, which obviously won't work because it's not a containery container...

```
16:56 $ kubectl get pod -o wide
NAME         READY   STATUS         RESTARTS   AGE   IP          NODE             NOMINATED NODE   READINESS GATES
hello-wasi   0/1     ErrImagePull   0          19s   10.1.0.38   docker-desktop   <none>           <none>
```

**Comment by itowlson** [comment]
If I roll back to before the first bootstrapping commit, the pods are scheduled to the appropriate `krustlet-*` nodes.  Possible red herring, but has something changed in the taints and tolerations stuff?

**Comment by itowlson** [comment]
Deleting the node and letting `just run-wasi` recreate it seemed to fix the scheduling problem - the integration test pods are now scheduled to the Krustlet nodes.  I noticed a change in #275 that the `start` method would `// Create the node. If it already exists, this will exit` where previously it would `"adopt" the node definition` (kubelet.rs, line 64).  So maybe having nodes around that were created by older builds of `krustlet-wasi` and `krustlet-wascc` was the problem, and the switch from adoption to exiting meant that the new kubelet didn't get run?

However, even with the pod scheduled and running, I now get a new integration test failure: the WASI pod logs, instead of commencing with `Hello, world!` are now reporting `"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Get https://172.27.91.118:3001/containerLogs/default/hello-wasi/hello-wasi: tls: received empty certificates message\",\"code\":500}\n"`...

(And `just run-wascc` still fails too.)

**Comment by thomastaylor312** [comment]
That looks like a cert issue @itowlson. Which means that something isn't working correctly with the serving cert bootstrap process

> Also now having a problem doing `just run-wasi` and `just run-wascc` concurrently (which I need to do to run the e2e tests):
> 
> ```
> Error: ApiError: certificatesigningrequests.certificates.k8s.io "hestia-tls" already exists: AlreadyExists 
> (ErrorResponse { status: "Failure", message: "certificatesigningrequests.certificates.k8s.io \"hestia-tls\" 
> already exists", reason: "AlreadyExists", code: 409 })
> 
> Caused by:
>     certificatesigningrequests.certificates.k8s.io "hestia-tls" already exists: AlreadyExists
> ```
> 
> (Here `hestia` is the name of the local machine.)

☝️ Also, with this, it is due to the hostname being the same. In the e2e tests I delete the CSR before starting the other. I figured this would only be a problem locally (as you would probably not be running a double krustlet on a normal node in a "real" environment), so maybe the `run-wasi` and `run-wascc` should just have something that does `kubectl delete csr $(hostname)-tls || true`

**Comment by thomastaylor312** [comment]
Oh and @bacongobbler I should have documented this:

> It looks as though reading from /dev/random blocks indefinitely.

That can happen on specific systems where it doesn't have the entropy to read from it. Changing it would make it insecure though. I think that we should probably set a variable like `RANDOM_SOURCE` with the default being `/dev/random` and an override in our justfile to use `/dev/urandom`

**Comment by bacongobbler** [comment]
bash exposes $RANDOM, where each read is unique. Not sure if it's cryptographically secure either, but that could be used as a source, and because it's bash it should work cross-platform.

Curious to see if there's prior art here for other projects
