### ISSUE TITLE
Thread panics when running multiple waSCC demos on the same port

### ISSUE THREAD

**Issue by wangyira** [deislabs/krustlet#288]
I ran into this problem when I tried running 2 waSCC demos at once. Since two examples are running on the same port (8080), the thread panicked and failed. After identifying the issue, I tried recreating the problem and one of the two scenarios would occur.

1. Use `kubectl apply` to create 2 pods from 2 examples. Only the 1st pod is running and the 2nd pod failed. Deleting the 2nd pod and running a `curl localhost:8080` on the 1st pod produces **Failed to handle request**. 
2. Run one demo following the instructions, then start running a second demo. `curl localhost:8080`won't produce any error, it will just show the output of the first demo. Deleting the pod created in the first demo, run `curl localhost:8080` again, it says **curl: (7) Failed to connect to localhost port 8080: Connection refused.**  In the `just run-wascc` terminal, this log can be found: **wascc actor executing <unnamed>' panicked at 'called Result::unwrap() on an Err value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }'.**

Currently, the only way to avoid this problem is to run one demo and delete the pod created,  before running another demo. 

Looking for suggestions to be able to run multiple examples concurrently on different ports automatically. @thomastaylor312 had mentioned in docker, an arbitrary port can be mapped to a port in the container. Kubernetes uses automatic mapping behind the scenes. It might be possible to take advantage of k8s and use it here.

**Comment by autodidaddict** [comment]
When waSCC binds an HTTP server capability provider to an actor, you can supply a `PORT` configuration variable. If this isn't supplied, then the HTTP server binding defaults to port `8080`.

If krustlet were to choose an arbitrary port number or assign port numbers with a monotonically increasing port number, this would prevent the panic due to trying to bind to an in-use port.

**Comment by thomastaylor312** [comment]
Yeah, for now the workaround is probably to change the pod definition to specify a different port. I think that we should make the waSCC provider use the `containerPorts` part of Pod spec to specify the port (instead of the `env` key) and then map it to a config underneath the hood. Combined with @autodidaddict's idea, I think it would be a good solution

**Comment by thomastaylor312** [comment]
Ok, I did some more thinking here. So I think the `containerPort` key doesn't mean the same thing in a wasm module context. There is no port to map to in the module, only on the host it is running on. So I think the behavior should be like this:

1. If `containerPort` is specified and `hostPort` is not, then automatically assign a port number
2. If `hostPort` is specified (whether or not `containerPort` is specified), then try to assign that port number. If it is taken, the pod will error

I'll work on figuring out how to tell kubernetes which port you are listening on. The data is in a `Service` but I am not sure what sets that. I think it is the kubelet, but I will double check

**Comment by thomastaylor312** [comment]
Ok so I looked more in to networking. I think that is probably a much bigger thing to tackle and is out of scope of this issue as it involves figuring out how to implement IP per pod networking. So for now, I would just figure out the automatic port mapping and then we can just rely on `NodePort` services as a workaround
