### ISSUE TITLE
Azure custom deployment fails

### ISSUE THREAD

**Issue by DerekStrickland** [deislabs/krustlet#485]
Following the Azure installation instructions, and the custom deployment fails on the newuserscript step with the following output.

Top level status says "Conflict"

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'newuserscript'. Error message: \"Enable failed: processing file downloads failed: failed to download file[0]: failed to download file: unexpected status code: actual=404 expected=200\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}

**Comment by kflansburg** [comment]
This line appears to be the issue:

https://github.com/deislabs/krustlet/blob/9439b957c316945672b5c94b19add39d9773aa7d/contrib/azure/azuredeploy.json#L124

It attempts to download from:
https://raw.githubusercontent.com/deislabs/krustlet/master/install_krustlet.sh
rather than:
https://raw.githubusercontent.com/deislabs/krustlet/master/contrib/azure/install_krustlet.sh

@bacongobbler

**Comment by kflansburg** [comment]
Assuming this is the only issue, I've pushed a patch to the `azure` branch. 

I do not have an Azure account, so someone else will need to try it. 

Here is deploy button pointing to that branch:
[![Deploy To
Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fdeislabs%2Fkrustlet%2Fazure%2Fcontrib%2Fazure%2Fazuredeploy.json)

**Comment by DerekStrickland** [comment]
Thanks @kflansburg!  This got me past that error, but a new one is now being thrown. I'll inspect it to make sure it's not something on my end and open a new issue if it seems it's not me.
