### ISSUE TITLE
Make pod eviction on shutdown optional

### ISSUE THREAD

**Issue by soenkeliebau** [deislabs/krustlet#523]
Currently the Krustlet automatically cordons the node and evicts all pods when a shutdown signal is received, which for most use cases following the K8S philosophy makes total sense.

For our use-case, in which we hand pods off to systemd to run it is quite valid to keep pods around even though the node they are assigned to is not online at the moment. The most relevant use case would be a restart of the krustlet.

I am happy to create a small pull request to introduce a parameter that allows disabling this behavior if that is something the team would consider?

**Comment by bacongobbler** [comment]
Hi @soenkeliebau. Thanks for bringing this conversation back up.

I guess the question proposed here is more philosophical. We originally designed Krustlet to follow the basic design principles of a kubelet; if a kubelet cordons the node and evicts all pods during a shutdown without a way to disable that behaviour, Krustlet should perform that behaviour as well. So why should Krustlet allow providers to opt out?

We should probably discuss whether it is our goal to

a) match Kubelet's design wherever possible, or
b) allow "escape hatches" for certain use cases (like this one)

This could set a dangerous precedent for the project which is why I'm hesitant to accept a PR for this behaviour. If we're to allow escape hatches that mismatch with the kubelet's behaviour, where do we draw the line when a feature is considered in-scope or out-of-scope for this project?

**Comment by soenkeliebau** [comment]
Hi @bacongobbler ,

I fully understand your position, we are aware that it is us who is deviating from the default behavior here.
Not sure if that is a discussion you want to have, otherwise I am happy to close the issue and we'll run of a fork that removes the drain functionality.

**Comment by soenkeliebau** [comment]
Picking this up after the discussion during last weeks community call and on Slack.

To bring everybody reading just here up to speed quickly, during the call we talked about whether the Kubelet actually evicts its pods on shutdown, or if this is left to the K8s control plane to handle.

@thomastaylor312 did some digging and came up with the following:

> So it looks like it actually tries to kill the pods (as in calling the underlying container runtime). So basically it is just making sure it doesn’t leave any resources hanging. What it does not do is cordon or evict based on what I can see. It also looks like this is enabled by a flag for graceful node shutdowns: https://github.com/kubernetes/kubernetes/blob/6572fe4d90173a1e97fda3e0cc28acc95e3f560a/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L221

> So my thinking is that we might want to add some sort of shutdown method to Provider with a default noop implementation. Because shutdown could be very different based on each runtime.

> We’d remove the direct logic from kubelet and just have it call shutdown rather than cordoning and evicting

I am happy to have a look at this and come up with a proposal of how this could be implemented, if the overall approach of having a shutdown function that providers can override is fine for everybody?

**Comment by bacongobbler** [comment]
SGTM

**Comment by thomastaylor312** [comment]
Yep, looks great to me!

**Comment by thomastaylor312** [comment]
@soenkeliebau Was just doing some milestone grooming. Would you like this assigned to you so someone else doesn't start work on it?

**Comment by soenkeliebau** [comment]
@thomastaylor312 feel free to assign this to me, yes (I have literally started looking at the code 5 minutes ago...)
