### ISSUE TITLE
Keep wasm pod running if krustlet service stopped

### ISSUE THREAD

**Issue by botieking98** [deislabs/krustlet#572]
Now I can build and run krustlet on my machine，but I encounted a new question, If I manully stop the krustlet service running in the background, the wasm pod is also stopped, this is not accepted for me when krustlet stopped and updated to latest version.
So Is is possible to keep wasm pod running always even if krustlet service is not availible ?

![image](https://user-images.githubusercontent.com/70674731/114159963-f31f0400-9958-11eb-81d7-87feb3983775.png)

If I manully start the krustlet service again, the wasm pod is running again from exited.

**Comment by bacongobbler** [comment]
Relevant: https://github.com/deislabs/krustlet/issues/523

it’s worth noting that krustlet manages the wasm process by spawning a new thread. To keep wasmtime running in the background would require

1. to detach the wasi instance as its own process using a process manager
2. To implement #523 so that pods are not evicted when the node is shut down.

Hope that helps clarify the situation.

**Comment by bacongobbler** [comment]
https://github.com/deislabs/krustlet/pull/571

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
